### PR TITLE
Fixes unusuable mod ban list

### LINKED ISSUE #106: Add a publicly available log
Make the logs found at https://leftypol.org/mod.php?/log public (without the IPs showing  of course).

### LINKED ISSUE #107: Fix ban log
Fix the ban logs layout issue found at https://leftypol.org/mod.php?/bans so they are more easily readable and usable.

### PR DESCRIPTION
**Pull request by nonmakina**

### CODE REVIEW

File: js/longtable/longtable.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ $.fn.longtable = function(fields, options, data) {
       });
       if (id !== undefined) {
         el.addClass("row").addClass("row_"+id);
-        el.css({position: "absolute", top: options.row_h * (id+1)});
+        //el.css({position: "absolute", top: options.row_h * (id+1)});
```
Comment (towards-a-new-leftypol) [inline js/longtable/longtable.js]: nuke these comments, the fact that this was done in js is a bug anyway.

**Review by towards-a-new-leftypol — CHANGES_REQUESTED** [review]

File: js/longtable/longtable.js (hunk 1 above)
Comment (nonmakina) [reply js/longtable/longtable.js]: done

**Review by towards-a-new-leftypol — APPROVED** [review]
